#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd "$2"; curl -L -f -O $PROXY "$1"; cd -
}

MATOMO_VERSION=5.13.0
MATOMO_ARCHIVE="matomo-${MATOMO_VERSION}.zip"
MATOMO_URL="https://github.com/matomo-org/matomo/releases/download/${MATOMO_VERSION}/${MATOMO_ARCHIVE}"

dl "$MATOMO_URL" /var/www
