#!/bin/bash -ex

DB_NAME=matomo
DB_USER=matomo
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

WEBROOT=/var/www/matomo

cd /var/www
unzip matomo-latest.zip

# configure apache
a2dissite 000-default
a2enmod headers
a2ensite matomo
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --batch --execute"

chown -R www-data:www-data /var/www/matomo
find /var/www/matomo/tmp -type f -exec chmod 644 {} \;
find /var/www/matomo/tmp -type d -exec chmod 755 {} \;

mysqladmin create $DB_NAME
$MYSQL_BATCH "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"
$MYSQL_BATCH "SET GLOBAL max_allowed_packet=268435456;" # 256 MB

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/index.php?module=Installation&action="
CURL="curl -c /tmp/cookie -b /tmp/cookie"

# HACK: work-around for Piwik being slow to get up
# sleep 5 || $CURL http://127.0.0.1/index.php

$CURL ${URL}systemCheck
$CURL ${URL}databaseSetup
$CURL ${URL}databaseSetup --data "host=127.0.0.1&username=$DB_USER&password=$DB_PASS&dbname=$DB_NAME&tables_prefix=matomo_&adapter=PDO\\MYSQL&submit=Next+%C2%BB"
$CURL ${URL}databaseCheck
$CURL ${URL}tablesCreation
$CURL ${URL}setupSuperUser
$CURL ${URL}setupSuperUser --data "login=$ADMIN_NAME&password=$ADMIN_PASS&password_bis=$ADMIN_PASS&email=$EMAIL&submit=Next+%C2%BB"
$CURL ${URL}firstWebsiteSetup
$CURL ${URL}firstWebsiteSetup --data "siteName=Example&url=http%3A%2F%2Fexample.org&timezone=UTC&ecommerce=0&submit=Next+%C2%BB"
$CURL ${URL}trackingCode
$CURL ${URL}trackingCode --data "site_idSite=1&site_name=Example"
$CURL ${URL}finished
$CURL ${URL}finished --data "site_idSite=1&site_name=Example"

rm -f /tmp/cookie

# configure mail and secure configuration file
CONF=/var/www/matomo/config/config.ini.php

sed -i '/^\[General\]$/a \
enable_trusted_host_check = 0' $CONF

sed -i '/^\[General\]$/a \
force_ssl = 1' $CONF


cat >> $CONF << EOF
[mail]
transport = "smtp"
host = "localhost"
EOF

chmod 640 $CONF

# stop services
service mysql stop
service apache2 stop
