#!/bin/bash -ex

DB_NAME=matomo
DB_USER=matomo
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

WEBROOT=/var/www/matomo

cd /var/www
unzip matomo-latest.zip

# configure apache
a2dissite 000-default
a2enmod headers
a2ensite matomo
a2enmod rewrite

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --batch --execute"

# hit cron job to download geoIP db
/etc/cron.monthly/geo-ip-update

# tweak mod_evasive to ensure that Matomo admin page(s) are accessible by default
sed -i '\|DOSPageCount| s|#||; \|DOSPageCount| s|[0-9]*$|5|' /etc/apache2/mods-available/evasive.conf

chown -R www-data:www-data /var/www/matomo
find /var/www/matomo/tmp -type f -exec chmod 644 {} \;
find /var/www/matomo/tmp -type d -exec chmod 755 {} \;

mysqladmin create $DB_NAME
$MYSQL_BATCH "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# curl based install
EMAIL=$(echo $ADMIN_MAIL | sed s/@/%40/)
URL="http://127.0.0.1/index.php?module=Installation&action="
CURL="curl -c /tmp/cookie -b /tmp/cookie"

$CURL ${URL}systemCheck
$CURL ${URL}databaseSetup
$CURL ${URL}databaseSetup --data "host=127.0.0.1&username=$DB_USER&password=$DB_PASS&dbname=$DB_NAME&tables_prefix=matomo_&adapter=PDO\\MYSQL&submit=Next+%C2%BB"
$CURL ${URL}databaseCheck
$CURL ${URL}tablesCreation
$CURL ${URL}setupSuperUser
$CURL ${URL}setupSuperUser --data "login=$ADMIN_NAME&password=$ADMIN_PASS&password_bis=$ADMIN_PASS&email=$EMAIL&submit=Next+%C2%BB"
$CURL ${URL}firstWebsiteSetup
$CURL ${URL}firstWebsiteSetup --data "siteName=Example&url=http%3A%2F%2Fexample.org&timezone=UTC&ecommerce=0&submit=Next+%C2%BB"
$CURL ${URL}trackingCode
$CURL ${URL}trackingCode --data "site_idSite=1&site_name=Example"
$CURL ${URL}finished
$CURL ${URL}finished --data "site_idSite=1&site_name=Example"

rm -f /tmp/cookie

# configure mail and secure configuration file
CONF=/var/www/matomo/config/config.ini.php

sed -i '/^\[General\]$/a \
enable_trusted_host_check = 0' $CONF

sed -i '/^\[General\]$/a \
force_ssl = 1' $CONF


cat >> $CONF << EOF
[mail]
transport = "smtp"
host = "localhost"
EOF

chmod 640 $CONF

# disable browser based cron - not required when cron job enabled
$MYSQL_BATCH "INSERT INTO matomo.matomo_option (option_name,option_value,autoload) values ('enableBrowserTriggerArchiving',0,1)";

# enable PHP GeoIP2
$MYSQL_BATCH "INSERT INTO matomo.matomo_option (option_name,option_value,autoload) values ('usercountry.location_provider','geoip2php',1)";

# ensure that cron log dir exists and has correct permissions
mkdir -p /var/log/matomo
chown www-data:www-data /var/log/matomo

# stop services
service mysql stop
service apache2 stop
