#!/bin/bash -e
# regenerate piwik secrets and mysql password

. /etc/default/inithooks

SALT=$(mcookie)
$INITHOOKS_PATH/bin/piwik_config.py "[superuser]" "salt" "$SALT"

PASSWORD=$(mcookie)
$INITHOOKS_PATH/bin/piwik_config.py "[database]" "password" "$PASSWORD"
$INITHOOKS_PATH/bin/mysqlconf.py --user=piwik --pass="$PASSWORD"

