#!/bin/bash -e
# regenerate matomo secrets and mysql password

. /etc/default/inithooks

SALT=$(mcookie)
$INITHOOKS_PATH/bin/matomo_config.py "[superuser]" "salt" "$SALT"

PASSWORD=$(mcookie)
$INITHOOKS_PATH/bin/matomo_config.py "[database]" "password" "$PASSWORD"
$INITHOOKS_PATH/bin/mysqlconf.py --user=matomo --pass="$PASSWORD"

