#!/bin/bash -e
# regenerate piwik secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/piwik/config/config.ini.php
SALT=$(mcookie)
PASSWORD=$(mcookie)

sed -i "s|salt.*|salt = \"$SALT\"|" $CONF
sed -i "0,/password/! {s/password.*/password = \"$PASSWORD\"/}" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=piwik --pass="$PASSWORD"

