#!/bin/bash -e
# set matomo admin password, email and domain

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/matomo.py --pass="$APP_PASS" --email="$APP_EMAIL" --domain="$APP_DOMAIN"

