#!/bin/bash -e
# set matomo admin password, email and domain

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
printf '%s' "$APP_PASS" | \
    $INITHOOKS_PATH/bin/matomo.py --pass-stdin \
        --email="$APP_EMAIL" --domain="$APP_DOMAIN"
